---

- name: Create sentinel container
  docker_container:
    name: sentinel
    image: '{{sentinel_image}}'
    state: started
    restart: yes
    networks_cli_compatible: yes
    networks:
      - name: '{{ docker_network_name }}'
    restart_policy: always
    volumes:
      - data:/dash
      - /home/{{dashd_user}}/dash.conf:/sentinel/dash.conf
    env:
      RPCHOST: dashd
      NETWORK: '{{dash_network}}'
