---

- name: Create DAPI container
  docker_container:
    name: dapi
    image: '{{dapi_image}}'
    state: started
    restart: yes
    networks_cli_compatible: yes
    networks:
      - name: '{{ docker_network_name }}'
    restart_policy: always
    command: 'npm run core' #npm run api?
    env:
      DASHCORE_RPC_HOST:     'dashd'
      DASHCORE_RPC_PORT:     '{{ dashd_rpc_port }}'
      DASHCORE_RPC_USER:     '{{ dashd_rpc_user }}'
      DASHCORE_RPC_PASS:     '{{ dashd_rpc_password }}'
      DASHCORE_ZMQ_HOST:     'dashd'
      DASHCORE_ZMQ_PORT:     '{{ dashd_zmq_port }}'
      DASHCORE_P2P_HOST:     'dashd'
      DASHCORE_P2P_PORT:     '{{ dashd_p2p_port }}'
      TENDERMINT_CORE_HOST:  'tendermint'
      TENDERMINT_CORE_PORT:  '26657'
      INSIGHT_URI:           'http://insight:3001/insight-api'
      API_JSON_RPC_PORT:     '3004'
      API_GRPC_PORT:         '3005'
      DRIVE_RPC_HOST:        'drive_api'
      DRIVE_RPC_PORT:        '6000'
      #DASHCORE_P2P_NETWORK: '{{ dash_network }}'
      #NETWORK:              '{{ dash_network }}'
