---

- name: Create js-machine container
  docker_container:
    name: js-machine
    image: '{{jsmachine_image}}'
    state: started
    restart: yes
    command: 'npm run abci'
    networks_cli_compatible: yes
    networks:
      - name: '{{ docker_network_name }}'
    env:
      DRIVE_UPDATE_STATE_HOST:             'drive_update_state'
      DRIVE_UPDATE_STATE_PORT:             '5000'
      DRIVE_API_HOST:                      'drive_api'
      DRIVE_API_PORT:                      '6000'
      RATE_LIMITER_ACTIVE:                 '{{ platfrom_state_transitions_limiter_enabled }}'
      RATE_LIMITER_MAX_TRANSITIONS_PER_ID: '100'
      RATE_LIMITER_PER_BLOCK_INTERVAL:     '36'
      RATE_LIMITER_PER_BAN_INTERVAL:       '17280'
      RATE_LIMITER_INTERVAL_PREFIX:        'ratelimiter.interval'
      RATE_LIMITER_BAN_PREFIX:             'ratelimiter.ban'
    volumes:
      - machine_leveldb:/usr/src/app/db
