---
- name: Set up environment
  hosts: all
  become: true
  tags: environment
  roles:
    - nickjj.user
    - nickjj.sshd
    # - nickjj.fail2ban
    - nickjj.iptables
    - nickjj.swapfile
    - nickjj.docker

- name: Set up masternode
  hosts: all
  tags: masternode
  become: true
  pre_tasks:
  - name: Create network
    docker_network:
      name: '{{ docker_network_name }}'
  roles:
    - dashd
    - sentinel
    - insight
    - dapi
