---
- name: Set up environment
  hosts: all
  become: true
  tags: environment
  roles:
    - nickjj.user
    - nickjj.sshd
    # - nickjj.fail2ban
    - nickjj.iptables
    - nickjj.swapfile
    - nickjj.docker
  post_tasks:
  - name: Install modules
    pip: 
      name: 
        - pymongo 
        - docker

- name: Set up masternode
  hosts: all
  tags: masternode
  become: true
  pre_tasks:
  - name: Create docker network
    docker_network:
      name: '{{ docker_network_name }}'
  - include: set_network.yml
  - set_fact:
      dashd_zmq: true
      dashd_indexes: true
    when: evo_services
  roles:
    - dashd
    - role: sentinel
      when: masternode
    - role: insight
      when: evo_services
    - role: dapi
      when: evo_services
    - role: drive
      when: evo_services
    - role: js-machine
      when: evo_services
